export const meta = {
  name: 'advance_rag_batch_c',
  description: 'Portfolio projects P1-P3: production-grade standalone RAG systems',
  phases: [{ title: 'build' }]
};

const CONV = args.conventions;

const SCHEMA = {
  type: 'object',
  properties: {
    project: { type: 'string' },
    files_created: { type: 'array', items: { type: 'string' } },
    tests_green: { type: 'boolean' },
    all_compiled: { type: 'boolean' },
    diagrams_count: { type: 'number' },
    issues: { type: 'string' }
  },
  required: ['project', 'files_created', 'tests_green', 'all_compiled', 'diagrams_count', 'issues']
};

phase('build');
log('building P1, P2, P3');
const r = await parallel([
  () => agent(CONV + '\n\nYOUR PROJECT: P1 — portfolio/enterprise-knowledge-assistant/\n\nBuild a standalone production-grade RAG SERVICE (FastAPI). Required layout:\n- pyproject.toml (uv; deps: fastapi, uvicorn[standard], chromadb, rank-bm25, sentence-transformers, pydantic, python-dotenv, rich, httpx, pytest)\n- app/config.py (env-driven settings), app/llm.py (OpenAI-compatible client via requests/httpx; OPENAI_API_KEY or YOLO_AUTO_* ; graceful 503-with-hint when none), app/retrieval.py (hybrid BM25+dense RRF + optional cross-encoder rerank), app/cache.py (semantic cache, cosine threshold), app/guardrails.py (PII redaction regexes + prompt-injection pattern filter), app/main.py (FastAPI: GET /health, GET /metrics (request counts, cache hit-rate, latency p50/p95 in-memory), POST /ingest, POST /query {question,k,threshold} -> cached answer or retrieve+rerank+generate with sources)\n- scripts/ingest.py (CLI: ingest ./data/sample_docs into persistent chroma)\n- data/sample_docs/ (write 6-8 realistic markdown policy/product docs yourself, ~200-400 words each)\n- tests/test_retrieval.py, tests/test_cache.py, tests/test_guardrails.py, tests/test_api.py (httpx TestClient; NO real LLM calls — mock app.llm; ALL must pass offline)\n- Dockerfile (python:3.12-slim + uv, non-root, healthcheck), docker-compose.yml (volume for vector store, env_file), .github/workflows/ci.yml (uv install + pytest), .env.example, README.md (pitch, architecture summary, quickstart, API table)\n- docs/PLANNING.md (problem, goals, non-goals, milestones), docs/DESIGN.md (>=5 mermaid: system context, containers, components, query sequence incl. cache+guardrail branches, deployment), docs/DEPLOYMENT.md (runbook: build/run/env table/scaling/backup/rollback)\n\nVERIFY: "cd portfolio/enterprise-knowledge-assistant && uv sync && uv run pytest -v" ALL GREEN; py_compile every .py; "uv run python -c "from app.main import app"" succeeds.', { label: 'p1', schema: SCHEMA }),
  () => agent(CONV + '\n\nYOUR PROJECT: P2 — portfolio/agentic-research-agent/\n\nBuild a standalone AGENTIC RAG system (LangGraph plan-and-execute + reflection) with a streaming API. Required layout:\n- pyproject.toml (uv; deps: langgraph, langchain-core, langchain-openai, langchain-ollama, chromadb, sentence-transformers, fastapi, uvicorn[standard], sse-starlette or plain StreamingResponse, python-dotenv, rich, pytest, httpx)\n- agent/state.py (typed AgentState: question, plan, steps, observations, reflections, answer, citations), agent/tools.py (vector_search over local chroma, metadata_filter_search, calculator), agent/graph.py (LangGraph: planner -> executor loop -> reflector (critique + one revision pass) -> synthesizer; conditional edges), agent/prompts.py\n- api/main.py (FastAPI: GET /health, POST /ask -> full answer with [n] citations, POST /ask/stream -> SSE token stream), api/routes.py\n- data/sample_docs/ (5-6 markdown research docs you write) + scripts/ingest.py\n- tests/test_graph.py (run graph with a FAKE chat model — deterministic canned responses — assert plan executed, reflection triggered on low-confidence marker, citations well-formed), tests/test_citations.py, tests/test_api.py (TestClient, mocked LLM; ALL pass offline)\n- Dockerfile, docker-compose.yml, .github/workflows/ci.yml, .env.example, README.md (pitch, quickstart, SSE example curl)\n- docs/PLANNING.md, docs/DESIGN.md (>=5 mermaid: context, agent state machine, tool-call sequence, streaming sequence, deployment), docs/DEPLOYMENT.md\n\nVERIFY: "cd portfolio/agentic-research-agent && uv sync && uv run pytest -v" ALL GREEN; py_compile every .py; import-check api.main.', { label: 'p2', schema: SCHEMA }),
  () => agent(CONV + '\n\nYOUR PROJECT: P3 — portfolio/rag-evaluation-harness/\n\nBuild a standalone RAG EVALUATION & MLOps harness. Required layout:\n- pyproject.toml (uv; deps: chromadb, sentence-transformers, rank-bm25, langchain-core, langchain-openai, langchain-ollama, ragas, datasets, pydantic, python-dotenv, rich, pytest)\n- harness/metrics.py (custom OFFLINE metrics: context keyword-coverage, answer relevancy via embedding similarity, faithfulness proxy via claim-context similarity; PLUS optional RAGAS metrics wrapped so missing LLM keys skip gracefully), harness/pipelines.py (PipelineA naive dense retriever, PipelineB hybrid BM25+dense RRF + rerank; both expose retrieve(question)->docs and generate(question,docs)->answer with injectable LLM), harness/runner.py (load JSONL eval set, run pipeline, collect per-question scores), harness/report.py (markdown + JSON report: per-metric means, A/B delta table), harness/gate.py (regression gate: compare against evals/baseline.json, exit code 1 if any metric drops > tolerance)\n- cli.py (argparse: "uv run python cli.py run --pipeline B --evals evals/dataset.jsonl --report out/report.md"; "uv run python cli.py gate --baseline evals/baseline.json")\n- evals/dataset.jsonl (8-10 questions with reference answers you author from data/sample_docs you also write: 5-6 markdown docs), evals/baseline.json (generated by running pipeline A offline with heuristic generator stub)\n- tests/test_metrics.py (known-good/known-bad triples produce expected ordering), tests/test_gate.py (pass + fail cases), tests/test_runner.py (stub LLM); ALL pass offline\n- Dockerfile, docker-compose.yml, .github/workflows/ci.yml (pytest + "cli.py gate" as the CI quality gate), .env.example, README.md (pitch, quickstart, how the gate blocks regressions)\n- docs/PLANNING.md, docs/DESIGN.md (>=5 mermaid: context, harness components, eval flow sequence, A/B comparison flow, CI gate state diagram), docs/DEPLOYMENT.md\n\nVERIFY: "cd portfolio/rag-evaluation-harness && uv sync && uv run pytest -v" ALL GREEN; py_compile every .py; "uv run python cli.py run --pipeline A --evals evals/dataset.jsonl --report out/report.md" completes offline (heuristic mode) and writes the report.', { label: 'p3', schema: SCHEMA })
]);

return r;