"""
RAG Fusion — Approach 2: From Scratch (framework-free)
======================================================
Same pattern as main.py (LangChain Chroma), but with ZERO LangChain RAG plumbing:

    LLM expands query into 3 variants
        -> each variant searched in RAW chromadb (dense vectors)
        -> ranked lists fused with Reciprocal Rank Fusion implemented in numpy (k=60)
        -> top-k fused docs sent to the LLM for the final answer

What "from scratch" means here:
- No LangChain retrievers, chains, or vector-store wrappers.
- chromadb is used through its native Python API (EphemeralClient).
- RRF is a ~15-line numpy implementation you can read in one sitting.

Run from project root:
    uv run python 07-advanced-rag-patterns/code/rag_fusion/approach_2_from_scratch.py
"""

import sys
import pathlib

# Windows console is cp1252; force UTF-8 output to avoid encoding errors
if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

# Project root (this file lives in <root>/07-advanced-rag-patterns/code/rag_fusion/)
sys.path.append(str(pathlib.Path(__file__).resolve().parents[3]))

import numpy as np
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

console = Console()

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
RRF_K = 60            # RRF constant (higher = flatter ranking curve)
NUM_VARIANTS = 3      # query variants generated by the LLM
TOP_K_PER_QUERY = 5   # docs retrieved per variant
FINAL_TOP_K = 3       # fused docs used for the final answer


# ---------------------------------------------------------------------------
# Stage 0: Corpus loading + raw chromadb index
# ---------------------------------------------------------------------------
def load_corpus() -> list[tuple[str, str]]:
    """Load sample txt/md files and chunk them. Returns (text, source) tuples."""
    data_dir = pathlib.Path(__file__).resolve().parents[3] / "data" / "samples"
    chunks: list[tuple[str, str]] = []
    for file_path in sorted(data_dir.iterdir()):
        if file_path.suffix.lower() not in (".txt", ".md"):
            continue
        content = file_path.read_text(encoding="utf-8")
        for para in content.split("\n\n"):
            para = para.strip()
            if len(para) < 20:
                continue
            for j in range(0, len(para), 500):
                piece = para[j:j + 500].strip()
                if piece:
                    chunks.append((piece, file_path.name))
    return chunks


def build_store(chunks: list[tuple[str, str]]):
    """Build an in-memory chromadb collection with precomputed dense vectors."""
    import chromadb
    from shared.config import get_embeddings

    embeddings = get_embeddings()
    texts = [c[0] for c in chunks]
    vectors = embeddings.embed_documents(texts)  # MiniLM, 384-dim, local & cached

    client = chromadb.EphemeralClient()
    collection = client.get_or_create_collection("rag_fusion_scratch")
    collection.add(
        ids=[f"doc_{i}" for i in range(len(chunks))],
        documents=texts,
        metadatas=[{"source": c[1]} for c in chunks],
        embeddings=vectors,
    )
    return client, collection, embeddings


# ---------------------------------------------------------------------------
# Stage 1: Query expansion (LLM, with heuristic fallback)
# ---------------------------------------------------------------------------
def expand_query(question: str) -> tuple[list[str], bool]:
    """Ask the LLM for NUM_VARIANTS rephrasings. Returns (variants, llm_ok)."""
    from shared.config import get_llm

    prompt = f"""Given the question: "{question}"

Generate {NUM_VARIANTS} different ways to rephrase this question for document retrieval.
Each variant should use different words, angles, or levels of specificity.
Output ONLY the {NUM_VARIANTS} queries, one per line, no numbering, no extra text."""

    try:
        llm = get_llm(temperature=0.7)
        response = llm.invoke(prompt)
        lines = [ln.strip() for ln in response.content.strip().split("\n") if ln.strip()]
        variants = lines[:NUM_VARIANTS] or [question]
        while len(variants) < NUM_VARIANTS:
            variants.append(question)
        return variants, True
    except Exception as e:
        console.print(f"[red]LLM unavailable ({type(e).__name__}).[/red]")
        console.print("[yellow]Hint: check YOLO_AUTO_API_KEY / OPENAI_API_KEY in .env.[/yellow]")
        # Heuristic fallback so the RRF mechanics are still demonstrable:
        words = [w for w in question.lower().split() if len(w) > 3]
        return [question, " ".join(words), f"explain {question}"], False


# ---------------------------------------------------------------------------
# Stage 2: Raw dense search per variant
# ---------------------------------------------------------------------------
def search(collection, embeddings, query: str, k: int = TOP_K_PER_QUERY):
    """One dense search against raw chromadb. Returns list of doc ids (ranked)."""
    vec = embeddings.embed_query(query)
    res = collection.query(query_embeddings=[vec], n_results=k)
    return res["ids"][0]


# ---------------------------------------------------------------------------
# Stage 3: Reciprocal Rank Fusion in numpy
# ---------------------------------------------------------------------------
def rrf_fuse(rank_lists: list[list[str]], k: int = RRF_K):
    """
    RRF: score(doc) = sum over lists of 1 / (k + rank), rank is 1-indexed.

    Returns list of (doc_id, score, per_list_ranks) sorted by score desc.
    """
    all_ids: list[str] = []
    seen: set[str] = set()
    for rl in rank_lists:
        for doc_id in rl:
            if doc_id not in seen:
                seen.add(doc_id)
                all_ids.append(doc_id)

    idx = {d: i for i, d in enumerate(all_ids)}
    scores = np.zeros(len(all_ids))
    ranks = np.full((len(rank_lists), len(all_ids)), -1, dtype=int)

    for list_i, rl in enumerate(rank_lists):
        for rank, doc_id in enumerate(rl, start=1):
            scores[idx[doc_id]] += 1.0 / (k + rank)
            ranks[list_i, idx[doc_id]] = rank

    order = np.argsort(-scores, kind="stable")
    return [(all_ids[i], float(scores[i]), ranks[:, i]) for i in order]


# ---------------------------------------------------------------------------
# Stage 4: Final answer (LLM, with graceful fallback)
# ---------------------------------------------------------------------------
def answer(question: str, docs: list[str]) -> None:
    from shared.config import get_llm

    context = "\n\n".join(f"[Doc {i+1}] {d}" for i, d in enumerate(docs))
    prompt = f"""Using ONLY the following context, answer the question.
If the context doesn't contain the answer, say so clearly.

Context:
{context}

Question: {question}

Answer:"""
    try:
        llm = get_llm(temperature=0.0)
        response = llm.invoke(prompt)
        console.print(Panel(response.content.strip(), title="[green]Final Answer[/green]",
                            border_style="green"))
    except Exception as e:
        console.print(f"[red]Could not generate answer ({type(e).__name__}).[/red]")
        console.print("[yellow]Showing the fused top-k context instead — that is what the "
                      "LLM would have been given:[/yellow]")
        for i, d in enumerate(docs, 1):
            console.print(f"[dim][Doc {i}] {d[:200]}{'...' if len(d) > 200 else ''}[/dim]")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> int:
    console.print(Panel("[bold magenta]RAG FUSION — FROM SCRATCH (raw chromadb + numpy RRF)[/bold magenta]",
                        subtitle="No LangChain retrievers/chains anywhere"))

    question = "How does vector-based retrieval work in a RAG system?"
    console.print(f"\n[bold]User Question:[/bold] {question}\n")

    # Stage 0
    chunks = load_corpus()
    console.print(f"Loaded {len(chunks)} chunks from data/samples/")
    try:
        _, collection, embeddings = build_store(chunks)
    except Exception as e:
        console.print(f"[red]Embeddings/vector store failed: {e}[/red]")
        console.print("[yellow]Hint: local MiniLM should already be cached; check network "
                      "or LOCAL_EMBEDDING_MODEL in .env.[/yellow]")
        return 0

    # Stage 1
    variants, llm_ok = expand_query(question)
    console.print(f"\nQuery variants ({'LLM' if llm_ok else 'heuristic fallback'}):")
    for i, v in enumerate(variants, 1):
        console.print(f"  [{i}] {v}")

    # Stage 2
    rank_lists = []
    for v in variants:
        ids = search(collection, embeddings, v)
        rank_lists.append(ids)
        console.print(f"  '{v[:50]}...' -> top: {ids[0]}")

    # Stage 3
    fused = rrf_fuse(rank_lists)
    table = Table(title=f"Fused Ranking (numpy RRF, k={RRF_K})", show_lines=True)
    table.add_column("Rank", width=5)
    table.add_column("Doc ID", width=10)
    table.add_column("RRF Score", justify="right")
    for i in range(len(variants)):
        table.add_column(f"Q{i+1}", justify="center", width=5)
    for rank, (doc_id, score, per_ranks) in enumerate(fused[:8], 1):
        table.add_row(str(rank), doc_id, f"{score:.4f}",
                      *[str(r) if r >= 0 else "-" for r in per_ranks])
    console.print(table)

    # Stage 4
    top_docs = [collection.get(ids=[doc_id])["documents"][0]
                for doc_id, _, _ in fused[:FINAL_TOP_K]]
    answer(question, top_docs)

    console.print("\n[bold green]Done.[/bold green] Framework-free RAG Fusion complete.\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
